@baseUrl = http://127.0.0.1
@cType = application/x-www-form-urlencoded
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzk5MjUzNzMsImxldmVsIjoiYXBwbGljYXRpb24iLCJ1c2VybmFtZSI6ImRqYW1icmVkIn0._dcYYTCHFMZMpTbtLbPKcukbsiJ8_8TdSeGAgLySa8Y

###
GET {{baseUrl}}/generate-hash/:qwerty

###
GET {{baseUrl}}

###
POST {{baseUrl}}/login
Content-Type: {{cType}}

username=djambred&password=:qwerty

###
POST {{baseUrl}}/pegawai
Authorization: Bearer {{token}}
Content-Type: {{cType}}

nama=tes&alamat=test&telepon=12345


### 
GET {{baseUrl}}/pegawai
Authorization: Bearer {{token}}